spring:
    application:
        name: ibs
    datasource:
        url: jdbc:postgresql://34.126.121.127:5432/testdb
        username: testuser
        password: testpassword
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                default_schema: AKADEMIK
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
    logging:
        level:
            org.hibernate.SQL: DEBUG
            org.hibernate.type.descriptor.sql.BasicBinder: TRACE
