spring:
    application:
        name: ibs
    datasource:
        url: jdbc:postgresql://localhost:15001/insurance2206083136
        username: testuser
        password: testpassword
    jpa:
        properties:
          hibernate:
              jdbc:
                lob:
                    non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
